export const GET_QUESTIONS_START = 'search/GET_QUESTIONS_START';
export const GET_QUESTIONS_SUCCESS = 'search/GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_ERROR = 'search/GET_QUESTIONS_ERROR';

export const GET_QUESTIONS_MORE_START = 'search/GET_QUESTIONS_MORE_START';
export const GET_QUESTIONS_MORE_SUCCESS = 'search/GET_QUESTIONS_MORE_SUCCESS';
export const GET_QUESTIONS_MORE_ERROR = 'search/GET_QUESTIONS_MORE_ERROR';

export const QUESTIONS_LIST_HAS_NO_MORE = 'search/QUESTIONS_LIST_HAS_NO_MORE';

export const SET_INITIAL_VALUE_TO_STATE = 'search/SET_INITIAL_VALUE_TO_STATE';
