export const ADD_ITEM_TO_SEARCH_HISTORY = 'search/ADD_ITEM_TO_SEARCH_HISTORY';
export const REMOVE_ITEM_FROM_SEARCH_HISTORY = 'search/REMOVE_ITEM_FROM_SEARCH_HISTORY';

export const SET_ARRAY_TO_SEARCHED_HISTORY = 'search/SET_ARRAY_TO_SEARCHED_HISTORY';
