export const GET_ANSWERS_BY_QUESTION_ID_START = 'answers/GET_ANSWERS_BY_QUESTION_ID_START';
export const GET_ANSWERS_BY_QUESTION_ID_SUCCESS = 'answers/GET_ANSWERS_BY_QUESTION_ID_SUCCESS';
export const GET_ANSWERS_BY_QUESTION_ID_ERROR = 'answers/GET_ANSWERS_BY_QUESTION_ID_ERROR';

export const GET_ANSWERS_BY_QUESTION_ID_MORE_START = 'answers/GET_ANSWERS_BY_QUESTION_ID_MORE_START';
export const GET_ANSWERS_BY_QUESTION_ID_MORE_SUCCESS = 'answers/GET_ANSWERS_BY_QUESTION_ID_MORE_SUCCESS';
export const GET_ANSWERS_BY_QUESTION_ID_MORE_ERROR = 'answers/GET_ANSWERS_BY_QUESTION_ID_MORE_ERROR';

export const ANSWERS_HAS_NO_MORE = 'answers/ANSWERS_HAS_NO_MORE';

export const COUNT_ANSWERS = 'answers/COUNT_ANSWERS';


export const PUBLISHING_ANSWER_START = 'answers/PUBLISHING_ANSWER_START';
export const PUBLISHING_ANSWER_SUCCESS = 'answers/PUBLISHING_ANSWER_SUCCESS';
export const PUBLISHING_ANSWER_ERROR = 'answers/PUBLISHING_ANSWER_ERROR';
